-- PostgreSQL is the sole durable store. UUIDs and secrets are generated by the
-- service so this migration requires no optional database extension.

CREATE TYPE companion_status AS ENUM ('active', 'suspended', 'retired');
CREATE TYPE gateway_status AS ENUM ('pending', 'active', 'revoked');
CREATE TYPE enrollment_status AS ENUM ('pending', 'claimed', 'expired', 'cancelled');
CREATE TYPE certificate_rotation_status AS ENUM ('pending', 'activated', 'expired', 'cancelled');
CREATE TYPE action_status AS ENUM ('queued', 'delivered', 'succeeded', 'failed', 'rejected', 'expired', 'cancelled');

CREATE TABLE owners (
    id UUID PRIMARY KEY,
    issuer TEXT NOT NULL,
    subject TEXT NOT NULL,
    email TEXT,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    last_login_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT owners_issuer_subject_unique UNIQUE (issuer, subject),
    CONSTRAINT owners_subject_nonempty CHECK (length(subject) BETWEEN 1 AND 255)
);

CREATE TABLE browser_oauth_attempts (
    id UUID PRIMARY KEY,
    state_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(state_digest) = 32),
    state_cookie_digest BYTEA NOT NULL CHECK (octet_length(state_cookie_digest) = 32),
    nonce_digest BYTEA NOT NULL CHECK (octet_length(nonce_digest) = 32),
    pkce_nonce BYTEA NOT NULL CHECK (octet_length(pkce_nonce) = 12),
    pkce_ciphertext BYTEA NOT NULL,
    return_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT browser_oauth_attempt_expiry CHECK (expires_at > created_at)
);

CREATE TABLE browser_sessions (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    csrf_digest BYTEA NOT NULL CHECK (octet_length(csrf_digest) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    user_agent_digest BYTEA CHECK (user_agent_digest IS NULL OR octet_length(user_agent_digest) = 32),
    CONSTRAINT browser_session_expiry CHECK (expires_at > created_at)
);
CREATE INDEX browser_sessions_owner_active_idx
    ON browser_sessions(owner_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE browser_ws_tickets (
    ticket_digest BYTEA PRIMARY KEY CHECK (octet_length(ticket_digest) = 32),
    session_id UUID NOT NULL REFERENCES browser_sessions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT browser_ws_ticket_expiry CHECK (expires_at > created_at)
);

CREATE TABLE companions (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES owners(id) ON DELETE RESTRICT,
    hardware_uid TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    status companion_status NOT NULL DEFAULT 'active',
    active_key_version INTEGER NOT NULL DEFAULT 1 CHECK (active_key_version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    last_seen_at TIMESTAMPTZ,
    CONSTRAINT companion_name_length CHECK (char_length(display_name) BETWEEN 1 AND 80),
    CONSTRAINT companion_uid_length CHECK (char_length(hardware_uid) BETWEEN 4 AND 128)
);
CREATE INDEX companions_owner_idx ON companions(owner_id, created_at);

CREATE TABLE companion_secret_versions (
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    key_version INTEGER NOT NULL CHECK (key_version > 0),
    kms_key_id TEXT NOT NULL,
    wrapped_dek BYTEA NOT NULL,
    secret_nonce BYTEA NOT NULL CHECK (octet_length(secret_nonce) = 12),
    secret_ciphertext BYTEA NOT NULL CHECK (octet_length(secret_ciphertext) = 48),
    crypto_version SMALLINT NOT NULL DEFAULT 1 CHECK (crypto_version = 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    accept_until TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    PRIMARY KEY (companion_id, key_version)
);

-- A gateway UUID is a stable logical identity and is intentionally independent
-- of any individual client certificate. Signed device envelopes bind this UUID;
-- certificate rotation therefore never changes the transcript identity.
CREATE TABLE gateways (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES owners(id) ON DELETE RESTRICT,
    status gateway_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    activated_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_proof_at TIMESTAMPTZ
);
CREATE INDEX gateways_owner_active_idx ON gateways(owner_id) WHERE status = 'active';

CREATE TABLE gateway_certificates (
    id UUID PRIMARY KEY,
    gateway_id UUID NOT NULL REFERENCES gateways(id) ON DELETE CASCADE,
    certificate_sha256 BYTEA NOT NULL UNIQUE CHECK (octet_length(certificate_sha256) = 32),
    spiffe_id TEXT,
    status gateway_status NOT NULL DEFAULT 'pending',
    valid_after TIMESTAMPTZ NOT NULL,
    valid_until TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    activated_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_proof_at TIMESTAMPTZ,
    CONSTRAINT gateway_certificate_validity CHECK (valid_until > valid_after),
    CONSTRAINT gateway_spiffe_nonempty CHECK (spiffe_id IS NULL OR length(spiffe_id) > 0)
);
CREATE INDEX gateway_spiffe_active_idx
    ON gateway_certificates(spiffe_id) WHERE spiffe_id IS NOT NULL AND status = 'active';
CREATE INDEX gateway_certificate_active_idx
    ON gateway_certificates(certificate_sha256) WHERE status = 'active';

-- The owner authorizes rotation by creating a short-lived, one-use challenge.
-- Activation proves possession of the replacement private key over mTLS. The
-- old certificate remains valid only until overlap_ends_at, allowing a bounded
-- reconnect window without changing the stable gateway UUID.
CREATE TABLE gateway_certificate_rotations (
    id UUID PRIMARY KEY,
    gateway_id UUID NOT NULL REFERENCES gateways(id) ON DELETE CASCADE,
    old_certificate_id UUID NOT NULL REFERENCES gateway_certificates(id) ON DELETE RESTRICT,
    new_certificate_id UUID REFERENCES gateway_certificates(id) ON DELETE RESTRICT,
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    status certificate_rotation_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    overlap_seconds INTEGER NOT NULL CHECK (overlap_seconds BETWEEN 60 AND 86400),
    activated_at TIMESTAMPTZ,
    overlap_ends_at TIMESTAMPTZ,
    CONSTRAINT gateway_rotation_expiry CHECK (expires_at > created_at),
    CONSTRAINT gateway_rotation_activation_fields CHECK (
        (status = 'activated' AND new_certificate_id IS NOT NULL AND activated_at IS NOT NULL
                              AND overlap_ends_at IS NOT NULL) OR
        (status <> 'activated')
    )
);
CREATE INDEX gateway_rotation_pending_idx
    ON gateway_certificate_rotations(gateway_id, expires_at) WHERE status = 'pending';
CREATE UNIQUE INDEX gateway_rotation_one_pending_idx
    ON gateway_certificate_rotations(gateway_id) WHERE status = 'pending';
CREATE INDEX gateway_rotation_overlap_idx
    ON gateway_certificate_rotations(old_certificate_id, overlap_ends_at)
    WHERE status = 'activated';

CREATE TABLE gateway_companions (
    gateway_id UUID NOT NULL REFERENCES gateways(id) ON DELETE CASCADE,
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    bound_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    unbound_at TIMESTAMPTZ,
    PRIMARY KEY (gateway_id, companion_id)
);
CREATE UNIQUE INDEX gateway_companion_active_binding_idx
    ON gateway_companions(companion_id) WHERE unbound_at IS NULL;

CREATE TABLE enrollment_challenges (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    hardware_uid TEXT NOT NULL,
    display_name TEXT NOT NULL,
    status enrollment_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ,
    claimed_gateway_id UUID REFERENCES gateways(id),
    companion_id UUID REFERENCES companions(id),
    CONSTRAINT enrollment_expiry CHECK (expires_at > created_at),
    CONSTRAINT enrollment_name_length CHECK (char_length(display_name) BETWEEN 1 AND 80)
);
CREATE INDEX enrollment_pending_idx
    ON enrollment_challenges(expires_at) WHERE status = 'pending';

CREATE TABLE device_sequences (
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    key_version INTEGER NOT NULL,
    last_sequence BIGINT NOT NULL DEFAULT 0 CHECK (last_sequence >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (companion_id, key_version),
    FOREIGN KEY (companion_id, key_version)
        REFERENCES companion_secret_versions(companion_id, key_version)
        ON DELETE CASCADE
);

CREATE TABLE device_requests (
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    request_id UUID NOT NULL,
    key_version INTEGER NOT NULL,
    envelope_sequence BIGINT NOT NULL CHECK (envelope_sequence > 0),
    nonce BYTEA NOT NULL CHECK (octet_length(nonce) = 16),
    transcript_sha256 BYTEA NOT NULL CHECK (octet_length(transcript_sha256) = 32),
    received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (companion_id, request_id),
    CONSTRAINT device_request_sequence_unique UNIQUE (companion_id, key_version, envelope_sequence)
);

CREATE TABLE device_events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    gateway_id UUID NOT NULL REFERENCES gateways(id) ON DELETE RESTRICT,
    envelope_sequence BIGINT NOT NULL CHECK (envelope_sequence > 0),
    event_type TEXT NOT NULL,
    observed_epoch BIGINT,
    boot_id BIGINT NOT NULL CHECK (boot_id BETWEEN 0 AND 4294967295),
    monotonic_ms BIGINT NOT NULL CHECK (monotonic_ms BETWEEN 0 AND 4294967295),
    body JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT device_event_unique UNIQUE (companion_id, event_id),
    CONSTRAINT event_type_format CHECK (event_type ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    CONSTRAINT observed_epoch_range CHECK (
        observed_epoch IS NULL OR observed_epoch BETWEEN 1577836800 AND 4102444800
    )
);
CREATE INDEX device_events_companion_cursor_idx ON device_events(companion_id, id);
CREATE INDEX device_events_companion_received_idx ON device_events(companion_id, received_at DESC);

CREATE TABLE companion_state_projections (
    companion_id UUID PRIMARY KEY REFERENCES companions(id) ON DELETE CASCADE,
    source_event_id UUID NOT NULL,
    source_envelope_sequence BIGINT NOT NULL CHECK (source_envelope_sequence > 0),
    vitals JSONB NOT NULL DEFAULT '{}'::jsonb,
    mood JSONB NOT NULL DEFAULT '{}'::jsonb,
    bond JSONB NOT NULL DEFAULT '{}'::jsonb,
    evolution JSONB NOT NULL DEFAULT '{}'::jsonb,
    mesh JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE owner_companion_cursors (
    owner_id UUID NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    last_read_event_id BIGINT NOT NULL DEFAULT 0 CHECK (last_read_event_id >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (owner_id, companion_id)
);

CREATE TABLE peer_history (
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    public_key BYTEA NOT NULL CHECK (octet_length(public_key) = 32),
    role TEXT NOT NULL CHECK (role IN ('client', 'repeater', 'room', 'sensor')),
    display_name TEXT NOT NULL DEFAULT '',
    seen_count BIGINT NOT NULL CHECK (seen_count BETWEEN 1 AND 4294967295),
    last_seen_epoch BIGINT,
    last_seen_boot_id BIGINT NOT NULL CHECK (last_seen_boot_id BETWEEN 0 AND 4294967295),
    last_seen_monotonic_ms BIGINT NOT NULL CHECK (last_seen_monotonic_ms BETWEEN 0 AND 4294967295),
    signal_scope TEXT CHECK (signal_scope IS NULL OR signal_scope = 'last_hop'),
    rssi_deci_dbm SMALLINT CHECK (rssi_deci_dbm IS NULL OR rssi_deci_dbm BETWEEN -2000 AND 0),
    snr_deci_db SMALLINT CHECK (snr_deci_db IS NULL OR snr_deci_db BETWEEN -500 AND 500),
    journal_sequence BIGINT NOT NULL CHECK (journal_sequence BETWEEN 1 AND 4294967295),
    source_envelope_sequence BIGINT NOT NULL CHECK (source_envelope_sequence > 0),
    first_received_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (companion_id, public_key),
    CONSTRAINT peer_signal_all_or_none CHECK (
        (signal_scope IS NULL AND rssi_deci_dbm IS NULL AND snr_deci_db IS NULL) OR
        (signal_scope = 'last_hop' AND rssi_deci_dbm IS NOT NULL AND snr_deci_db IS NOT NULL)
    ),
    CONSTRAINT peer_epoch_range CHECK (
        last_seen_epoch IS NULL OR last_seen_epoch BETWEEN 1577836800 AND 4102444800
    )
);
CREATE INDEX peer_history_companion_recent_idx ON peer_history(companion_id, updated_at DESC);

CREATE TABLE remote_actions (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES owners(id) ON DELETE RESTRICT,
    companion_id UUID NOT NULL REFERENCES companions(id) ON DELETE CASCADE,
    idempotency_key TEXT NOT NULL,
    request_sha256 BYTEA NOT NULL CHECK (octet_length(request_sha256) = 32),
    action_type TEXT NOT NULL CHECK (action_type IN (
        'companion.pet', 'companion.feed', 'companion.play', 'companion.listen_once',
        'sync.pull', 'clock.set', 'mesh.introduce', 'message.send'
    )),
    parameters JSONB NOT NULL,
    key_version INTEGER NOT NULL CHECK (key_version > 0),
    wire_nonce BYTEA NOT NULL CHECK (octet_length(wire_nonce) = 16),
    wire_parameters BYTEA NOT NULL CHECK (
        octet_length(wire_parameters) BETWEEN 1 AND 16384
    ),
    wire_signature BYTEA NOT NULL CHECK (octet_length(wire_signature) = 32),
    status action_status NOT NULL DEFAULT 'queued',
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    first_delivered_at TIMESTAMPTZ,
    device_accepted_epoch BIGINT,
    completed_at TIMESTAMPTZ,
    result JSONB,
    CONSTRAINT remote_action_idempotency UNIQUE (owner_id, idempotency_key),
    CONSTRAINT remote_action_expiry CHECK (expires_at > created_at),
    CONSTRAINT remote_action_idempotency_length CHECK (char_length(idempotency_key) BETWEEN 8 AND 128),
    CONSTRAINT remote_action_device_accept_epoch CHECK (
        device_accepted_epoch IS NULL OR device_accepted_epoch BETWEEN 1577836800 AND 4102444800
    )
);
CREATE INDEX remote_actions_delivery_idx
    ON remote_actions(companion_id, expires_at, created_at)
    WHERE status IN ('queued', 'delivered');
CREATE INDEX remote_actions_owner_idx ON remote_actions(owner_id, created_at DESC);

CREATE TABLE action_delivery_attempts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action_id UUID NOT NULL REFERENCES remote_actions(id) ON DELETE CASCADE,
    gateway_id UUID NOT NULL REFERENCES gateways(id) ON DELETE RESTRICT,
    instance_id UUID NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    transport TEXT NOT NULL DEFAULT 'websocket',
    accepted_by_socket BOOLEAN NOT NULL
);
CREATE INDEX action_attempts_action_idx ON action_delivery_attempts(action_id, attempted_at DESC);

CREATE TABLE audit_log (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    actor_type TEXT NOT NULL CHECK (actor_type IN ('owner', 'gateway', 'device', 'system')),
    actor_owner_id UUID REFERENCES owners(id),
    actor_gateway_id UUID REFERENCES gateways(id),
    companion_id UUID REFERENCES companions(id),
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    request_id UUID,
    source_address INET,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT audit_action_format CHECK (action ~ '^[a-z][a-z0-9_.-]{0,95}$')
);
CREATE INDEX audit_log_owner_cursor_idx ON audit_log(actor_owner_id, id);
CREATE INDEX audit_log_companion_cursor_idx ON audit_log(companion_id, id);

CREATE TABLE rate_limit_buckets (
    scope TEXT NOT NULL,
    subject_hash BYTEA NOT NULL CHECK (octet_length(subject_hash) = 32),
    window_started_at TIMESTAMPTZ NOT NULL,
    request_count INTEGER NOT NULL CHECK (request_count > 0),
    expires_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (scope, subject_hash)
);
CREATE INDEX rate_limit_expiry_idx ON rate_limit_buckets(expires_at);

CREATE FUNCTION reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only';
END;
$$;
CREATE TRIGGER audit_log_no_update
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();

CREATE FUNCTION notify_remote_action() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('kitsu_remote_actions', NEW.companion_id::text);
    RETURN NEW;
END;
$$;
CREATE TRIGGER remote_action_notify
    AFTER INSERT ON remote_actions
    FOR EACH ROW EXECUTE FUNCTION notify_remote_action();

COMMENT ON TABLE companion_secret_versions IS
    'Contains only KMS-wrapped DEKs and AES-256-GCM ciphertext; never plaintext companion secrets.';
COMMENT ON TABLE audit_log IS
    'Append-only security audit. Application code must exclude credentials, tokens, proofs, and plaintext message secrets from details.';
